/* Generated by scripts/import-question-pool.mjs. */
(function (global) {
  "use strict";
// src/data/questionPool/bossQuestions.js

const bossModeTags = ["challenge_boss", "shadow_challenge"];

function q(base) {
  return {
    difficulty: "boss",
    difficultyLevel: 5,
    fontColor: "#FFFFFF",
    timeLimit: 900,
    modeTags: bossModeTags,
    ...base,
  };
}

function btn(id, label, color, extra = {}) {
  return { id, label, color, ...extra };
}

const bossStroopSeeds = [
  ["红色", "#3483FF", ["红色", "#FF8A00", "#FF3D5A"], ["橙色", "#3483FF", "#FF8A00"], ["蓝色", "#FF3D5A", "#3483FF"]],
  ["绿色", "#FF5CB0", ["绿色", "#00FFC7", "#00FF9D"], ["青色", "#FF5CB0", "#00FFC7"], ["粉色", "#00FF9D", "#FF5CB0"]],
  ["黄色", "#A855F7", ["黄色", "#FF8A00", "#FFD600"], ["橙色", "#A855F7", "#FF8A00"], ["紫色", "#FFD600", "#A855F7"]],
  ["黑色", "#FFFFFF", ["黑色", "#333333", "#000000"], ["深灰色", "#FFFFFF", "#333333"], ["白色", "#000000", "#FFFFFF"]],
  ["蓝色", "#FF5CB0", ["蓝色", "#A855F7", "#3483FF"], ["紫色", "#FF5CB0", "#A855F7"], ["粉色", "#3483FF", "#FF5CB0"]],
];

const colorStroopBossQuestions = Array.from({ length: 20 }, (_, index) => {
  const seed = bossStroopSeeds[index % bossStroopSeeds.length];
  const [prompt, fontColor, a, b, c] = seed;

  return q({
    id: `color_stroop_boss_${String(index + 1).padStart(3, "0")}`,
    type: "color_stroop",
    prompt,
    fontColor,
    options: [
      {
        id: "btn_1",
        label: a[0],
        color: a[1],
        textColor: a[2],
      },
      {
        id: "btn_2",
        label: b[0],
        color: b[1],
        textColor: b[2],
      },
      {
        id: "btn_3",
        label: c[0],
        color: c[1],
        textColor: c[2],
      },
    ],
    correctAction: "btn_3",
    trap: "三色Stroop干扰",
    implementationLevel: "P2",
  });
});

const visualBossTemplates = [
  {
    prompt: "点最大的",
    trap: "大小陷阱",
    correctAction: "btn_3",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A", { scale: 1.8, blur: 0, brightness: "light" }),
      btn("btn_2", "按钮2", "#3483FF", { scale: 1.2, blur: 2, brightness: "medium" }),
      btn("btn_3", "按钮3", "#00FF9D", { scale: 0.6, blur: 4, brightness: "dark" }),
    ],
  },
  {
    prompt: "点最小的",
    trap: "大小陷阱",
    correctAction: "btn_3",
    options: [
      btn("btn_1", "按钮1", "#00FF9D", { scale: 0.6, blur: 4, brightness: "dark" }),
      btn("btn_2", "按钮2", "#3483FF", { scale: 1.2, blur: 2, brightness: "medium" }),
      btn("btn_3", "按钮3", "#FF3D5A", { scale: 1.8, blur: 0, brightness: "light" }),
    ],
  },
  {
    prompt: "点最亮的",
    trap: "亮度陷阱",
    correctAction: "btn_3",
    options: [
      btn("btn_1", "按钮1", "#FFFFFF", { scale: 1.6, blur: 0, brightness: "light" }),
      btn("btn_2", "按钮2", "#FFD600", { scale: 1.0, blur: 2, brightness: "medium" }),
      btn("btn_3", "按钮3", "#333333", { scale: 0.7, blur: 4, brightness: "dark" }),
    ],
  },
  {
    prompt: "点最暗的",
    trap: "亮度陷阱",
    correctAction: "btn_3",
    options: [
      btn("btn_1", "按钮1", "#333333", { scale: 1.6, blur: 4, brightness: "dark" }),
      btn("btn_2", "按钮2", "#FFD600", { scale: 1.0, blur: 2, brightness: "medium" }),
      btn("btn_3", "按钮3", "#FFFFFF", { scale: 0.7, blur: 0, brightness: "light" }),
    ],
  },
  {
    prompt: "点最模糊的",
    trap: "清晰度陷阱",
    correctAction: "btn_3",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A", { scale: 1.4, blur: 5, brightness: "dark" }),
      btn("btn_2", "按钮2", "#3483FF", { scale: 1.0, blur: 2, brightness: "medium" }),
      btn("btn_3", "按钮3", "#00FF9D", { scale: 0.7, blur: 0, brightness: "light" }),
    ],
  },
];

const visualTrapBossQuestions = Array.from({ length: 15 }, (_, index) => {
  const template = visualBossTemplates[index % visualBossTemplates.length];

  return q({
    id: `visual_trap_boss_${String(index + 1).padStart(3, "0")}`,
    type: "visual_trap",
    prompt: template.prompt,
    options: template.options,
    correctAction: template.correctAction,
    trap: template.trap,
    implementationLevel: "P1",
  });
});

const actionBossSeeds = [
  ["点两次", "quick_tap"],
  ["长按三秒", "long_press"],
  ["快点一下", "long_press"],
  ["长按一下", "quick_tap"],
  ["先点再松手", "long_press"],
  ["先长按再点", "quick_tap"],
  ["连续双击", "long_press"],
  ["轻触一下", "long_press"],
  ["别点然后再点", "tap"],
  ["点一下然后停下", "wait"],
];

const actionBossQuestions = Array.from({ length: 15 }, (_, index) => {
  const [prompt, correctAction] = actionBossSeeds[index % actionBossSeeds.length];

  return q({
    id: `action_boss_${String(index + 1).padStart(3, "0")}`,
    type: "action",
    prompt,
    options: null,
    correctAction,
    trap: "动作多层指令",
    implementationLevel: "P2",
  });
});

const doubleNegativeBossSeeds = [
  ["别不不要点", "tap"],
  ["别不不要滑", "swipe_down"],
  ["不要不不点", "tap"],
  ["你敢不不按", "tap"],
  ["禁止不不不动", "tap"],
  ["别不不要滑", "swipe_right"],
  ["别不不要滑", "swipe_up"],
  ["禁止不不不动", "tap"],
  ["禁止不不不动", "tap"],
  ["不要不不点", "tap"],
];

const doubleNegativeBossQuestions = doubleNegativeBossSeeds.map(([prompt, correctAction], index) =>
  q({
    id: `double_negative_boss_${String(index + 1).padStart(3, "0")}`,
    type: "double_negative",
    prompt,
    options: null,
    correctAction,
    trap: "三重否定",
    implementationLevel: "P2",
  })
);

const logicBossSeeds = [
  ["冰是热的吗?", "btn_false"],
  ["火是冷的吗?", "btn_false"],
  ["太阳从西方升起吗?", "btn_false"],
  ["1+1=3吗?", "btn_false"],
  ["水会流动吗?", "btn_true"],
];

const logicReversalBossQuestions = logicBossSeeds.map(([prompt, correctAction], index) =>
  q({
    id: `logic_reversal_boss_${String(index + 1).padStart(3, "0")}`,
    type: "logic_reversal",
    prompt,
    options: [
      { id: "btn_true", label: "对" },
      { id: "btn_false", label: "错" },
    ],
    correctAction,
    trap: "常识反转",
    implementationLevel: "P0",
  })
);

const chaosBossSeeds = [
  {
    prompt: "红不蓝绿选哪个?",
    options: [
      btn("btn_1", "绿", "#FF3D5A"),
      btn("btn_2", "蓝", "#FF3D5A"),
      btn("btn_3", "蓝", "#3483FF"),
    ],
    correctAction: "btn_2",
  },
  {
    prompt: "选不是最大的",
    options: [
      btn("btn_1", "蓝", "#00FF9D", { scale: 1.6 }),
      btn("btn_2", "绿", "#00FF9D", { scale: 1.0 }),
      btn("btn_3", "红", "#FF3D5A", { scale: 0.6 }),
    ],
    correctAction: "btn_1",
  },
  {
    prompt: "看到红字别点蓝色",
    options: [
      btn("btn_1", "蓝", "#FF3D5A", { textColor: "#FF3D5A" }),
      btn("btn_2", "红", "#FF3D5A", { textColor: "#3483FF" }),
      btn("btn_3", "绿", "#00FF9D", { textColor: "#FF3D5A" }),
    ],
    correctAction: "btn_1",
  },
  {
    prompt: "选中间就别选左右",
    options: [
      btn("btn_1", "左", "#FF3D5A", { position: "left" }),
      btn("btn_2", "中", "#3483FF", { position: "middle" }),
      btn("btn_3", "右", "#00FF9D", { position: "right" }),
    ],
    correctAction: "btn_3",
  },
  {
    prompt: "选颜色文字不一致",
    options: [
      btn("btn_1", "绿", "#00FF9D"),
      btn("btn_2", "红", "#3483FF"),
      btn("btn_3", "蓝", "#3483FF"),
    ],
    correctAction: "btn_2",
  },
];

const chaosBossQuestions = Array.from({ length: 15 }, (_, index) => {
  const item = chaosBossSeeds[index % chaosBossSeeds.length];

  return q({
    id: `chaos_boss_${String(index + 1).padStart(3, "0")}`,
    type: "chaos",
    prompt: item.prompt,
    options: item.options,
    correctAction: item.correctAction,
    trap: "多层干扰",
    implementationLevel: "P2",
  });
});

const bossQuestions = [
  ...colorStroopBossQuestions,
  ...visualTrapBossQuestions,
  ...actionBossQuestions,
  ...doubleNegativeBossQuestions,
  ...logicReversalBossQuestions,
  ...chaosBossQuestions,
];
  global.QuestionPoolParts = global.QuestionPoolParts || {};
  global.QuestionPoolParts.boss = bossQuestions;
})(window);
