/* Generated by scripts/import-question-pool.mjs. */
(function (global) {
  "use strict";
// src/data/questionPool/hardQuestions.js

const hardModeTags = ["single_level_3", "challenge_hard", "shadow_challenge"];

function q(base) {
  return {
    difficulty: "hard",
    difficultyLevel: 4,
    fontColor: "#FFFFFF",
    timeLimit: 1000,
    modeTags: hardModeTags,
    ...base,
  };
}

function btn(id, label, color, extra = {}) {
  return { id, label, color, ...extra };
}

const similarColorPairs = [
  ["red", "红色", "#FF3D5A", "orange_red", "橙红色", "#FF6B6B", "blue", "蓝色", "#3483FF"],
  ["blue", "蓝色", "#3483FF", "purple", "紫色", "#6D43FF", "yellow", "黄色", "#FFD600"],
  ["green", "绿色", "#00FF9D", "cyan", "青色", "#00FFC7", "pink", "粉色", "#FF5CB0"],
  ["yellow", "黄色", "#FFD600", "orange", "橙色", "#FF8A00", "purple", "紫色", "#A855F7"],
  ["black", "黑色", "#000000", "dark_gray", "深灰色", "#333333", "white", "白色", "#FFFFFF"],
  ["white", "白色", "#FFFFFF", "light_gray", "浅灰色", "#EEEEEE", "black", "黑色", "#000000"],
  ["pink", "粉色", "#FF5CB0", "light_red", "浅红色", "#FF7CA8", "green", "绿色", "#00FF9D"],
  ["cyan", "青色", "#00FFC7", "light_blue", "浅蓝色", "#7FDBFF", "purple", "紫色", "#A855F7"],
];

const colorHardQuestions = similarColorPairs.flatMap((pair, pairIndex) => {
  const [aId, aLabel, aColor, bId, bLabel, bColor, cId, cLabel, cColor] = pair;

  return [0, 1, 2].map((_, innerIndex) =>
    q({
      id: `color_hard_${String(pairIndex * 3 + innerIndex + 1).padStart(3, "0")}`,
      type: "color",
      prompt: `点${aLabel}`,
      options: [
        btn(aId, aLabel, aColor),
        btn(bId, bLabel, bColor),
        btn(cId, cLabel, cColor),
      ],
      correctAction: bId,
      trap: "相近颜色干扰",
      implementationLevel: "P1",
    })
  );
});

const stroopPairs = [
  ["red", "红色", "#FF3D5A", "blue", "蓝色", "#3483FF"],
  ["yellow", "黄色", "#FFD600", "green", "绿色", "#00FF9D"],
  ["purple", "紫色", "#A855F7", "orange", "橙色", "#FF8A00"],
  ["black", "黑色", "#000000", "white", "白色", "#FFFFFF"],
];

const colorStroopHardQuestions = Array.from({ length: 16 }, (_, index) => {
  const [aId, aLabel, aColor, bId, bLabel, bColor] = stroopPairs[index % stroopPairs.length];

  return q({
    id: `color_stroop_hard_${String(index + 1).padStart(3, "0")}`,
    type: "color_stroop",
    prompt: aLabel,
    fontColor: bColor,
    options: [
      {
        id: "btn_1",
        label: aLabel,
        color: bColor,
        textColor: aColor,
      },
      {
        id: "btn_2",
        label: bLabel,
        color: aColor,
        textColor: bColor,
      },
    ],
    correctAction: "btn_2",
    trap: "Stroop干扰",
    implementationLevel: "P1",
  });
});

const directionHardSeeds = [
  ["往左滑", "swipe_right"],
  ["往右滑", "swipe_left"],
  ["往上滑", "swipe_down"],
  ["往下滑", "swipe_up"],
  ["点左侧", "click_right"],
  ["点右侧", "click_left"],
  ["点上方", "click_bottom"],
  ["点下方", "click_top"],
  ["别点左边", "click_left"],
  ["别点右边", "click_right"],
  ["不要向上滑", "swipe_up"],
  ["不要向下滑", "swipe_down"],
  ["左边按钮", "click_right"],
  ["右边按钮", "click_left"],
  ["顶端按钮", "click_bottom"],
];

const directionHardQuestions = directionHardSeeds.map(([prompt, correctAction], index) =>
  q({
    id: `direction_hard_${String(index + 1).padStart(3, "0")}`,
    type: "direction",
    prompt,
    options: null,
    correctAction,
    trap: "方向反转",
    implementationLevel: "P0",
  })
);

const doubleNegativeHardSeeds = [
  ["别不点左边", "click_right"],
  ["别不要向右滑", "swipe_left"],
  ["不要不按", "tap"],
  ["你敢不点吗", "tap"],
  ["不许不点", "tap"],
  ["不要不左滑", "swipe_right"],
  ["别不按下", "tap"],
  ["不准不动", "wait"],
  ["不许不要按", "tap"],
  ["不要不动", "wait"],
];

const doubleNegativeHardQuestions = doubleNegativeHardSeeds.map(([prompt, correctAction], index) =>
  q({
    id: `double_negative_hard_${String(index + 1).padStart(3, "0")}`,
    type: "double_negative",
    prompt,
    options: null,
    correctAction,
    trap: "多重否定",
    implementationLevel: "P2",
  })
);

const logicHardSeeds = [
  ["冰是冷的吗?", "btn_true"],
  ["火是热的吗?", "btn_true"],
  ["太阳从东边升起吗?", "btn_true"],
  ["1+1=2吗?", "btn_true"],
  ["白天有太阳吗?", "btn_true"],
  ["水是干的吗?", "btn_false"],
  ["草是蓝色的吗?", "btn_false"],
  ["猫会飞吗?", "btn_false"],
  ["鱼会游泳吗?", "btn_true"],
  ["雪是热的吗?", "btn_false"],
];

const logicReversalHardQuestions = logicHardSeeds.map(([prompt, truthButton], index) =>
  q({
    id: `logic_reversal_hard_${String(index + 1).padStart(3, "0")}`,
    type: "logic_reversal",
    prompt,
    options: [
      { id: "btn_true", label: "对" },
      { id: "btn_false", label: "错" },
    ],
    correctAction: truthButton === "btn_true" ? "btn_false" : "btn_true",
    trap: "常识反转",
    implementationLevel: "P0",
  })
);

const visualTemplates = [
  {
    prompt: "点最大的",
    trap: "大小陷阱",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A", { scale: 1.6 }),
      btn("btn_2", "按钮2", "#3483FF", { scale: 1.0 }),
      btn("btn_3", "按钮3", "#00FF9D", { scale: 0.6 }),
    ],
    correctAction: "btn_3",
  },
  {
    prompt: "点最小的",
    trap: "大小陷阱",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A", { scale: 0.6 }),
      btn("btn_2", "按钮2", "#3483FF", { scale: 1.0 }),
      btn("btn_3", "按钮3", "#00FF9D", { scale: 1.6 }),
    ],
    correctAction: "btn_3",
  },
  {
    prompt: "点最亮的",
    trap: "亮度陷阱",
    options: [
      btn("btn_1", "按钮1", "#FFFFFF", { brightness: "light" }),
      btn("btn_2", "按钮2", "#FFD600", { brightness: "medium" }),
      btn("btn_3", "按钮3", "#333333", { brightness: "dark" }),
    ],
    correctAction: "btn_3",
  },
  {
    prompt: "点最暗的",
    trap: "亮度陷阱",
    options: [
      btn("btn_1", "按钮1", "#333333", { brightness: "dark" }),
      btn("btn_2", "按钮2", "#FFD600", { brightness: "medium" }),
      btn("btn_3", "按钮3", "#FFFFFF", { brightness: "light" }),
    ],
    correctAction: "btn_3",
  },
  {
    prompt: "点最模糊的",
    trap: "清晰度陷阱",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A", { blur: 4 }),
      btn("btn_2", "按钮2", "#3483FF", { blur: 2 }),
      btn("btn_3", "按钮3", "#00FF9D", { blur: 0 }),
    ],
    correctAction: "btn_3",
  },
];

const visualTrapHardQuestions = Array.from({ length: 20 }, (_, index) => {
  const template = visualTemplates[index % visualTemplates.length];

  return q({
    id: `visual_trap_hard_${String(index + 1).padStart(3, "0")}`,
    type: "visual_trap",
    prompt: template.prompt,
    options: template.options,
    correctAction: template.correctAction,
    trap: template.trap,
    implementationLevel: "P1",
  });
});

const actionHardSeeds = [
  ["快按一下", "long_press"],
  ["长按一下", "quick_tap"],
  ["快速点两下", "long_press"],
  ["别按", "tap"],
  ["停止", "tap"],
];

const actionHardQuestions = actionHardSeeds.map(([prompt, correctAction], index) =>
  q({
    id: `action_hard_${String(index + 1).padStart(3, "0")}`,
    type: "action",
    prompt,
    options: null,
    correctAction,
    trap: "动作反转",
    implementationLevel: "P1",
  })
);

const chaosHardSeeds = [
  {
    prompt: "点数字不同的",
    options: [
      btn("btn_1", "1", "#FF3D5A"),
      btn("btn_2", "1", "#3483FF"),
      btn("btn_3", "2", "#00FF9D"),
    ],
    correctAction: "btn_1",
  },
  {
    prompt: "点颜色不同的",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A"),
      btn("btn_2", "按钮2", "#FF3D5A"),
      btn("btn_3", "按钮3", "#3483FF"),
    ],
    correctAction: "btn_2",
  },
  {
    prompt: "选两个一样的",
    options: [
      btn("btn_1", "AA", "#FF3D5A"),
      btn("btn_2", "AA", "#3483FF"),
      btn("btn_3", "AB", "#00FF9D"),
    ],
    correctAction: "btn_3",
  },
  {
    prompt: "点左边不是红色的",
    options: [
      btn("btn_1", "按钮1", "#FF3D5A"),
      btn("btn_2", "按钮2", "#FF3D5A"),
      btn("btn_3", "按钮3", "#00FF9D"),
    ],
    correctAction: "btn_1",
  },
  {
    prompt: "点最长的文字",
    options: [
      btn("btn_1", "长文字", "#FF3D5A"),
      btn("btn_2", "更长的文字", "#3483FF"),
      btn("btn_3", "长", "#00FF9D"),
    ],
    correctAction: "btn_3",
  },
];

const chaosHardQuestions = chaosHardSeeds.map((item, index) =>
  q({
    id: `chaos_hard_${String(index + 1).padStart(3, "0")}`,
    type: "chaos",
    prompt: item.prompt,
    options: item.options,
    correctAction: item.correctAction,
    trap: "混沌干扰",
    implementationLevel: "P2",
  })
);

const hardQuestions = [
  ...colorHardQuestions,
  ...colorStroopHardQuestions,
  ...directionHardQuestions,
  ...doubleNegativeHardQuestions,
  ...logicReversalHardQuestions,
  ...visualTrapHardQuestions,
  ...actionHardQuestions,
  ...chaosHardQuestions,
];
  global.QuestionPoolParts = global.QuestionPoolParts || {};
  global.QuestionPoolParts.hard = hardQuestions;
})(window);
